- name: Build and push Docker image
  hosts: STAGE_SERVERS_WEB
  vars:
    docker_username: "shantibb"
    docker_password: "cHq-FP9-GYa-Hqr"
    docker_image: "shantibb/backend:latest"
    project_source: "/root/wallet_project"

  tasks:
    - name: Docker login
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Pull docker image
      community.docker.docker_image_pull:
        name: "{{ docker_image }}"
        platform: amd64

    - name: Restart docker compose
      block:
      - name: Down
        community.docker.docker_compose_v2:
          project_src: "{{ project_source }}"
          state: absent

      - name: Up
        community.docker.docker_compose_v2:
          project_src: "{{ project_source }}"
        register: output

      - name: Prune
        community.docker.docker_prune:
          containers: true
          images: true
          networks: true
          volumes: true
